apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: object-storage-root
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dXjtcA1+npjj,iv:+qPsnTlHkbME12FoUpd/qDAyJHioZi4JMM/0DXNMG3M=,tag:iMIZmRBECgS07VxnJ1nF8A==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gQ/kKe9W6yabKQ932ZevIiYc,iv:bosY6kpJK3qmaCyNNX8W/wocppzCZBlp4jXgrwTtxBk=,tag:m3G/O+oBCXt3C7MxfI88uA==,type:str]
            ADMIN_PASSWORD: ENC[AES256_GCM,data:W11Rk6BJ9TwX9SX02mrINYZRtNFwse9T,iv:Z9O8Eu1lxv1q9e/m8p6RKYQL53Ig10+aWfo98CftiSc=,tag:w0w5WCONbO7fKbeHCyWNMA==,type:str]
        - name: zot-credentials
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dGaZ4RlGvipg,iv:kYWBm/MBUP8Z0CVOVZloX6Y8wqOoamrKh5pIHLQjA+Y=,tag:2hUvzd/F5TUghfxLyc/NGw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DwcvZO6cmmGNaXdjFfYocU6V,iv:mCdgDblwQU1tekx1L6bFlCzL5/KPvwqp+yJXFhKqbp0=,tag:KrLv+mXAdBEDxrU5uB0qjg==,type:str]
            htpasswd: ENC[AES256_GCM,data:bA8ZzUWHdCnZW3hTSBMRvPCkFA34LVyrtH1+Od9JtC6FmAFF/RyqWsJsVKV7whRazhUYe7YBZUTzTEUNg0KFICJr8cSqXLiFp23L+iLE52RNTmT3uCflJjGM+RwhFYs6wj1rtg18CaDvbpmYy/FWQ+YRW7Jod+dsuR8VwlDXg0IGRxpITw==,iv:azJhRqyA3VUqGPX3vYhvKHrxQxkXxQg/zoOaC/InNV0=,tag:DVokYBB67G0dSgQ3bw7PYQ==,type:str]
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:btEJ4siobFjD,iv:kCC2UtNxeTALDzHwTKkR2EBpkS9jaCFaBvHvuUbHHXA=,tag:RCXzQyozeWeR9p+QTMHi4w==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nXUGkKnPr1nJiccI+IO8PC0S,iv:+i2Y23WIByA6w3mQ8I6S8nithEGZHSbZPFFcR4F5Zjk=,tag:g8DR8D4gB4iCTzOp9Wet/Q==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:PIts,iv:KyEhfOY4Z8QSpVwsUHREC5BZCLCYp3q01aTwRgRPxDQ=,tag:Ns9zzhqnE2oGPstMitlZAQ==,type:str]
            password: ENC[AES256_GCM,data:zLEI,iv:POlxgHRGMNqRf/MJoxlcWtqtLqcL/qjkNSZ0ow9R5d0=,tag:qaQm/50FJuSFEHLxBWJ2DA==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:QF8+,iv:MCV7pSNyKSg99sNA0drh/Cr4eemdBgXw+myKruQ5vt0=,tag:o9wiqZlqPt7t9AZJKwo0rQ==,type:str]
        - name: openfga-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:nnJmAP1cA8MYD8g=,iv:xYKPK3P1I59+WSyDA9HD90bIBNItf5jpyfIeltFwtME=,tag:8xunHh+a3NEqK4obVsBDSQ==,type:str]
            datastore_uri: ENC[AES256_GCM,data:MyGJOFCaDjk14b7oqMWrCCt/vI8h8iPabhNYu5bEj3KIuw61Igy+OU5QWBQTLHFe9jNUyvu3RtZhOrfJJV20CVpksY9zQzGa/m2Hp9tfH4ypRyf4q8E=,iv:AnZ7rcUE9hSf374B7xHGnwXvv0H1BIGbcksuWaD3HLE=,tag:SwF+nZEdfJIgxqLm4DjhAA==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:xQhH02kNREhktJk4hMCE8DjdGXTfVStEl87oLcJVt+m8CsyjMzfVeL0fPgnfndZ1nz4vCgRZOfCWqmU1PqVC9AGL3IZeq/o6kmVScHWHlE+qm1TTT/c=,iv:cTdQp+XBDp1YLXJJbZqCTYnlgPBVe24gnyyJwsb+HtA=,tag:zpZWkexa5EOCOsQvqnxFzQ==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Haj5ne/4oU1kGkcYI+tmIgQaYohlZ+SsH7mXtZ8RvVGlYOnqtbw7Z5lXHPAlYm/DkSg7HbW49AmhzWCBpeb3aT1NsWgIy0ncQ1sLY6203n8K4uX94A==,iv:7JdxW+7YnvkM0ZK378XSOTBbvFfj/vPBezLJ2jSWp8o=,tag:M6X5Kvg2Qt5rPtz5KX3dug==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:GNC6DOGZcyEagh4d0scx9O+Q6CibJFdYTGi8YT4lhr/QCpFtUdh5ZJy20+DmjDQs++x9iHMe3/ara/J4D0KODCc7u2g92jLfliEE2D35iUsdxoM=,iv:wx9rmIqVxuqEXqoL25953ApVzJ7Hb21skiBwG6p5xbs=,tag:lRSFgKBkEog8Vl+JWBaAqQ==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:HloX4o9h3tR7XS06ta/Qn15wYVmJGS8GHkXmuabsBtULO0NRzc6qcqF+b7wIE26GQ8B++lt04T35H6GaYeF87ZLwutDAhZpei1cunF559Um+NGAPUDU=,iv:ONeMWStH+CYcs8sJRdb4jc+5ulKi498y9C+GOPlT7i8=,tag:gCTiG6yhOQBXj5d865gxqw==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:t+nu1H5DlGB1PiWDMmtZPlxqSrfUbHYEhzfo8cQROw==,iv:pEYhHvsOvZx2iOLnuqcb/hRiXXgw0LBXWGLT9Z4qI0k=,tag:VYz6gEPUI/J0lQZsnqpf0w==,type:str]
            secretsCookie: ENC[AES256_GCM,data:zoeDe+Z37pXEbun+K4kzbEhYkkEu/FnfX8dHzGhSeJFvxW8U5P0ZJg==,iv:gCfqFylsDJRq4MyZiwFJ4eVekJNF/DtbQaOkuEdy8HI=,tag:enbbKkcgpzRGoRakuLWmQw==,type:str]
            secretsCipher: ENC[AES256_GCM,data:7fxwg8RTaW5LJnW9VUa3JQfgIyBHRRVfNh+qRcRfhYM=,iv:6ajA8XhJDfkBQF0vMD31pisIjVdFuUFgl215rMftV1k=,tag:NtTEjsb4IhD1ajnXH/ik7w==,type:str]
            dsn: ENC[AES256_GCM,data:nJXTkvOoToc+Gt4ktHc3caFibPerYNXZPhdUtjtXTi8lgSN4xQmEc6Uu4unJoqP8jmJs2O4y4bMz60F/ZvHqDM6uhT7C1kXF+tRt9yXsRNfFSvVYKw==,iv:HlLgNqAQfN7SB/nGvLrbJz8Wfs2X2CT9JaAVu9MSiMQ=,tag:ejFpKnYowoy0JUAFIgfKHg==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:QyIPvJuZuXudHRGDwUml6y6iaQOOBbjGqP0fJfVvsDrFeJYowAe65H1l6IELFO8hJsv6aVyEA9lKRerCv0KztYLqgubV,iv:59Nm6Ga7AtB3kLuUtrR8yPXgz3NAZrpYVIt9GgWfcoA=,tag:X3MibVmod/ibzyUlSsZ+qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZmE0KzFXMi9JWlU5WDl6
            NFVJVU0xVDJwamR6a2NkNys0S3RpQnBUYlNzCm1qbk5iaisrN0daT3ZCT1BsY2l5
            cDVFd2ZQWEEvMTdOVHdiS2IwbjY4Z1UKLS0tIHc0SFNoRXE1VUlGMzVSb3VNQU5G
            eWNHaXJOK1VIZTg0dU5CK1NKZG5DdWcKv8Ixan6/Ebxp3XA31lTvq/RAMxyfOEew
            PdL7DzblpRIvFkv8ztbnXBE/2/Ri3LLZY1UqVS/JUMuyxgioi5M6sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T13:25:01Z"
    mac: ENC[AES256_GCM,data:L6ttV3HpU/coJx3ZS1EpfhX8FItVTV1FllhGfp8Zmm30hekRbx454RMgMvVeTwPnCvaX9eF06wyYoxQvLAcjBFdyh/aLhmLMLKK7p5Krkq5we4wZUthNihzJsV9CAKydWft3waj5QqftU/MY9c6u9oIvfbl3fl/mk5crgLlqwx4=,iv:N5k4i+N9DHavC9u5eXiOIfmig9HjztIrmOfI+AzbiL0=,tag:FbWIztkTcFs1gYPIU6mikA==,type:str]
    version: 3.13.1
