apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: object-storage-root
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QnOYFr+v4IDK,iv:MPFA3N4K3sBWnZvHbwDFBemECikLrW2BDz338btcs08=,tag:PBDYpQ8OOaXoDsYDB6mWCA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DP80bQMsnj3vHhMBSni4V99A,iv:ZbgQYI74MLtGPNtZqCrNOtGlfMcJ0JZ+ePYwc5lXccY=,tag:oLj4wRb1KXrxkGGc+IkC3Q==,type:str]
            ADMIN_PASSWORD: ENC[AES256_GCM,data:SpGhlHK4Jv7SdFmd6zei3XdinYqVbeR6,iv:cl/62lFhelMUixadf1kifTerdrsos73/G7kJgcss3ug=,tag:ZBeGwamC4UVFStKvhttW/A==,type:str]
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WFdCTQXiZr9F,iv:XkZtPq+rGKwOLlWV39NxQsscGkjI2Vlm9hPatnGUsDY=,tag:Ofd240x0F/qBdZ/O0t9OAA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gNf7mweBMDk39i5kIXvAGnt/,iv:klaEZZX36QY30Jx2l+RCV1vIK6fWiOJdx9beRPpZtlA=,tag:OT1WnaljFuY9xmPqIuPfsA==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:898l,iv:8JHdDvhPxUuZPNToWwrKbG+b8h5DEmADJbvG2bQaUJI=,tag:YJzswyLpRWuWUPnWUZkWtQ==,type:str]
            password: ENC[AES256_GCM,data:W8Vd,iv:sj5xK3QBtO8plDCapWRSlBWsQfZutEM5pKVA1xuNkJM=,tag:yN6G7WK1EKfqANgO3hDaug==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:STJ5,iv:bUunEld+i6i5aoTok7COacXtyckamRuT1/aE7hk8zQA=,tag:iUfxedCQSw1Z9O4W+GKhfA==,type:str]
        - name: openfga-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:erQaRkdhuzOgHxg=,iv:B1RHr0Xfm6VeEQNKgxy/TabEqecD9haUwqHlRwkXCUo=,tag:B/ftGStFRT54eE9rdY8M5Q==,type:str]
            datastore_uri: ENC[AES256_GCM,data:ShvlC/2gNnH+WIl14/l+bn8RR4ZoRDd03VqnvLUkfJjI1lue7AmsVzXp/YgxLHZtG5HYpgqllBvpoZJFkPQYLRnX1Uu0I4Lrw8IaKjvoSZnVMjzEqPw=,iv:5I2MkjVVXw80uhvbN0nCCQfuzbxrTcxV+3beQOFwjaQ=,tag:iJjLioR80Zgxdrm/K5LfUQ==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Di21l6pUnWz3hT9Gb4IXIPedjD8BzLsY31dtYGDN+BoCy62aGVajINBqzNC6DFSdOqIWKzVurjoSBdLIts+cf76DeyqEyEO9DzrYrbYzssw+SOCAtxA=,iv:fw0nB01kZR7d+eeC+bFxz6smja/pcN+Uoj6/rILVfbY=,tag:7s+ZETaCSReynTDl71eiag==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:dcBurcU1Ab/mB6McNfcOlEf4L6SNTfEEBq/RyVl/HD+Kzrnu1bMIm+k8un83l9HXx9N9f4VoXXTKZpeRav27fZhwCj9RtTKwpGtHAOeD4zGBz5NjFg==,iv:2bOCobMolngE3Ao6IcS69/dza5zvPsdHTOH616A1VEw=,tag:LVAQyzP162p0yJFxFCBSHA==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:9GFevqVQuVRYoXSI7vhAxIeRo7UXVQnNSwlNnggTcc2qnxgdg83ufoAtAArSAdxH+RS1IKgDGvGsHLqu4wOzuWvjz8/3TccuYVf9oF2RWf0rGxk=,iv:aSO+D+dWEohwlCHELasWTXUfHKwf5/FUBD08QnAmDGI=,tag:wN+pYRSTdScv52eszcUm3w==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Sf4a1Wu8+8QCtH6SFbyUm7N9ki1i+VouTsdY60TepiWkEpok54ByVtacn/CtwxG8Pz0GEOv1FkbxWQjICMVfcatAQ5gnQgFtgl89KDmG2+s8fvaf4kQ=,iv:1mjWuHipeL5zHZqIkFOktWQRZJJGrvEvtgbHfBiD0Rg=,tag:bimmMfzbym2V1HPheSHfNA==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:P4MCuVi4zPghi29ZW3AMWAw5SZW3tYxUD4daZgwt3A==,iv:SvTXbQctcGwgn3zy4VJolI7gpXubXD3xE9Drf3Ekpic=,tag:YjwhMFZqvgc0eUd8Jiplew==,type:str]
            secretsCookie: ENC[AES256_GCM,data:UyAPdcnM9Se8NfSo+vooWQ/tOB6zUQIEw0XRpQIQBhB+LqVj+9eszQ==,iv:9YBrpqqM+OADTzE81akSw3LIR2SrEG+E2CehkITIZ5A=,tag:zJ38Dc4qdZkEj026SBgeJg==,type:str]
            secretsCipher: ENC[AES256_GCM,data:Mv6cIO5DrQKEZRjuymq/HjYhCkIOUgYL7HMu3IjJ8Hk=,iv:RKDFIfStgRo61O00JR2GdkPL9N6P9fe34lSU2dinx9U=,tag:6ucT7w6tJWBim2g2orPDlg==,type:str]
            dsn: ENC[AES256_GCM,data:cYaxu2LONBWBvekX2FS5ZdB27Sqbu6bU2Ugw+qXfYcCVQtLL1jz86TKVhrD4dc66EuxXI/pFJUWYvJgqT3SwIQHjatr2P9R2TaZEzgO+1bavFxAWpg==,iv:2p4DpChMJf20f1llxCN+kZub34OFOhLN0doU+Rwoqj4=,tag:ep8/1Y9jlaN9JcIG2qaTWw==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:1HhD+I4+Wv+whnhbkFo9A/AChKmiQK/aVJQsgoyV1uwokP0jdQj/Qq2eldC7j5FJ8ez9pjmNaYDD0cVHBeyimkqhV/ar,iv:SAlHCtFKDNecUe6tPok9Zh2jrD46fN5pYgGoAIhIdWs=,tag:DiLjatmj5lg5GdLF0LDpmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSGppSzRqRWNpcmJuYkdB
            czhTWFBRZGZUQ25LRTB6UTNlZ3ZVRnhKQ0hvCi9tcFg2RGMyUHVBZExZRE52MFpK
            aEZvMjZOangxZGtHT2J0OHorVTNsVG8KLS0tIGZFKzJGTDQ1U0FFVDNFYWh6ODVM
            dXJ0VVBpQmxodzdMRGcrRlpmajJxVWMKEeZCugzPhLF3nBv7dAmeYs9W0ZUvhKmu
            Leb0A6QJptE5C5zItOT58mLFG3XT0XwWZbcpklInqI4fcsvU/7vMNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T12:55:20Z"
    mac: ENC[AES256_GCM,data:3n6nfYK9Imwd2OqZLitCqYfZGHNdOvN5es9W5UvdjzWNisoRBVd+TruixBxFU+DvDPfBYAZpVx0552RlfBA9XDgsm3swNyrdMc1EQvEROIKZ6kaqrGELaCbiR/Rq3Zj7EDu8SuhHmi66QkBVGrd9XyXluzInc0LiDE9MkYodepw=,iv:y7fmnxg7ZLltsWhR55fyS0YvFFSCuLefEJD/7EGethw=,tag:zCiA4f1IQEjMa/o/wYe6tg==,type:str]
    version: 3.13.1
