apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: object-storage-root
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KBWrW2lyD7JE,iv:s5nS1lD9AlrLorXIwrVLFXhA3AUKOnK53Gyw/09v5cQ=,tag:wjQfpz3FFeiWYPtn0+k/Mg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P5bTCFobYacKqrpqb8qi+SnU,iv:4s7t7VAEEYEtImjKy3K/cMEv3/F6UsDp1QoXwKON2Vk=,tag:WeEaeU4tj+12NfdKnRh1mw==,type:str]
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9gxseLU=,iv:gPQ8CDfC0NfzNAVkYMBgECOTqegKIvBKBiJ53zMMj2I=,tag:SK5hpSj8d3Mqu5Z7M0xXqA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sbsZdSIqSESoHfDZX68=,iv:/N62PnZ/bMeNc8k3+AfZqLHgJvYFF/Hwj6YQtw5xHHA=,tag:cQhYF10JH/LqT6ngskQCGg==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:IC3M,iv:8592T8Pjm/z0IpusIan2s8Efrql1Muw2D3E3aJeoUpY=,tag:NfxqP0pc43KRKWu5oHU6oQ==,type:str]
            password: ENC[AES256_GCM,data:Jsbq,iv:xnNG0i3cYDBrl6W5h2S4vt1hJ6duIy3YRpH1enz+htc=,tag:erHM50Hw6Q/S464ecUs4Tw==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:4Ks6,iv:ndcF/mRE3hMRUumoFFBTNLLr07gdd/+Z3vrH+NRiYzM=,tag:kgBDh5lj4JQMa2ZaJ0+4oQ==,type:str]
        - name: openfga-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:XGoNFNkTfVJtiik=,iv:LEjdO8mpfiw4TNpJtkhAyEg7SooXzkvbtXwdRU7kPiA=,tag:AdTmRDkXBJvM6jwLyUfV4Q==,type:str]
            datastore_uri: ENC[AES256_GCM,data:Joa6sNfUZZgoPBQC43SDyXniLJ+SAHCc3WRGFmIzAQbcjusklsT+u+vo4lGwBTYRUHRaU3+3nrtk2xTbjWVrFGBmt+xY84gVBdcVhVIjkMzuwJLRXlQ=,iv:2cwTo3TMtZZj953BlKUMDwGUWbNFgdx9+wLV0bx89SU=,tag:w6NTXNAKBJ5X0Ga1IuFzoQ==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:XBLzYKes6YitC7zuj/nJ41a/bWs/gkLLf0y1HWicqjzXrS7Rco1AKldRFoGTs3V8QarXG2LwH+7cTDzuQsH6pH1TwQsvc+vvtcL2+LhjIKLxIu3v4bs=,iv:+Tk9s6YEwyf20EeWC23UF+MoFKv4YKVMBk1wjmA3xUc=,tag:kyG9BnfIsmwXU5ByCBpL0w==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Ka5aO/he8Y26HruK8sPHnHOh1KnYhak7bnneyocjNpQT9Xv1z0Cy0aZIMkD0i+4MaVjh2qNHX2ygaw2ebHZsQV64KGnudtAhtrOXXG12+UEdEzgVYQ==,iv:5MBSN/vsdXcLj8QkCLBiToJKqeEbHgIqXZ4/ZOTpbEs=,tag:5LpZ34sSrt6qa6nK3cmywQ==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:kg/zm2PT9gt4egn+yd8cOKV2bJV9B8Xan4lByMQjIn5xDvGacyy1a/kTthBeDA2NFjoQjdGs5uQGMfIvsD0FxAgevmRapGptLPIDFd0CsQ/7BA0=,iv:BHOoRVV0iJhMIbpy7P06rWtifW9jFX4CoHjHOzdjvn8=,tag:GdZ/LtfoCjEd/Ez7j20KNg==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Ix6cKgTtZ2+mwNl5qkGPWjNO+084KYavmOS6v9ptO88+r+IK26xjU6qUgeFg+Js1fpc1zJzAeGwZ3EwYwUZa8bFnxzThsTVQIap7eY314/qyJpMlJfM=,iv:AFQmnFkXsaoGlGdK0jOAFM3+l/62x+5n+zrKf0Ts7/M=,tag:Av4NURGqC2i3U6xjBgtR5g==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:vXG4M9kQADf77+bqnCbzktVNNeZXkwiIqzzpuMynSQ==,iv:LfZ8NgoSFzj0XQfOdlLSr7+rX7YUhtHbY3/Jnh5HZRA=,tag:cwpue96ClamXPDkcnNay2Q==,type:str]
            secretsCookie: ENC[AES256_GCM,data:+WpU/T/e1LpbHbhIyZGln2cjBW9e7C6kNPeTHtgXzSBEXCk83nATCA==,iv:cJk1noTUq+t6MPAizqi871sCBFQLpv+Mxa2jaQJLRSc=,tag:W/aiMe77rELW0XKt/PM+Aw==,type:str]
            secretsCipher: ENC[AES256_GCM,data:1eaXZqBHiDIDNHhMd5DqvcIf8TlehZ9INEiaRPvSj7Y=,iv:EKRJt1CbwjeAI0/bGIF+DqrbCYNZDEFfYnlWRbdOOQQ=,tag:JmIMTUcT6DoyVHLC+QwJVw==,type:str]
            dsn: ENC[AES256_GCM,data:UQ8+hauCigRAmtu5dpirpcYSfTgCPcyWht1jjMWIJuAMieOIiLQ1adf7T5yl+MYhlxLWmIrSSB6B6BZ5uSUEmfAODz89/CXSfkgNXC2vVPWU5Z6Wrg==,iv:hIjtqdooeYw1n33zupKu/LNluK4cj4jKfsjYILEA4dY=,tag:J+I719zaRF8wl2o7VWbiVA==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:r1Nd9NTrbbeAAL11q3eEAMt1p5hpXsN2+H9szHzZfTyqpzWVgBWd/WzQ7O/6g2eDx2SnCLPiNeZje3Gt8vXW7WzIqKQX,iv:AhoSXwMxfMUV3q0KIPmbPE6z+/X0pln70FTJZzQjWdA=,tag:NBpRwmNUBUhVtnDwAnllEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ajJYN1pnNllYS3FpcjlN
            aTRCVDV3dDFHdW96ejJVY0VySEd1KzExS1RJCk5NQmxUeDdNcTBycWNjdW1ZZGdB
            TFd6WGtyOGo3UWF5NGZBRURQWmEvU2MKLS0tIC9ydUtrNUJnYis1eXZSOUM5bm1j
            YzdQU0VmbWE5Q0w5d0Mrc3hhZyt6eTgKqQf0hFEkaV8OVx5o3jS6t575xYIy7a20
            /mwntB2nq6cZgjaJTQgjfJCWmTlCWcCsJGXGtzo6U2B9eZYPQ45H7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T12:22:32Z"
    mac: ENC[AES256_GCM,data:Fn35utj2lMITS8m1NM6gjLHal0CJdbB1n4AMkpqcenrptspSFljkzmwNFCZew0CQrpLhG4w/NhUaQfzlP+bGv+UI+rmePKWNX7+lmnklOHSwpP8FCXN7ecgmtFmtAWddHg0T6HUKBdXAQhlCdIWm82dRK7ciPlwFaKL6J8R/yew=,iv:p+NI4ibZuWHr/K1kGnXR4ScjSrPl4/dn6BcNCWy//SU=,tag:NbsaoC37J4EgzSVxfHzjLg==,type:str]
    version: 3.13.1
