// Code generated by ogen, DO NOT EDIT.

package catalog

import (
	"fmt"

	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// DeleteProductNoContent is response for DeleteProduct operation.
type DeleteProductNoContent struct{}

// ErrorStatusCode wraps Problem with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RFC 9457 problem details. Served as `application/problem+json` by services and by the edge alike, so
// a generated client has one error branch rather than two.
// Ref: #/components/schemas/Problem
type Problem struct {
	// `about:blank`, except where two errors share a status code and a client handles them differently.
	// That case takes a `urn:problem-type:<service>:<slug>` URN — never a dereferenceable URL, which
	// would put an error taxonomy into the flat public URL namespace.
	Type string `json:"type"`
	// A stable, human-readable summary. Does not vary with the instance.
	Title string `json:"title"`
	// The HTTP status, duplicated in the body.
	Status int `json:"status"`
	// Instance-specific and safe to show a user. Never a stack trace, a query, or an internal hostname.
	Detail OptString `json:"detail"`
	// The W3C Trace Context trace-id of the failing request, so a user-reported error reaches its trace.
	// Supplied from the active span, not by the handler.
	TraceID OptString `json:"trace_id"`
	// Field-level validation failures, populated from the generated validator. Absent when the failure is
	// not a validation failure.
	Errors []ProblemErrorsItem `json:"errors"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetTraceID returns the value of TraceID.
func (s *Problem) GetTraceID() OptString {
	return s.TraceID
}

// GetErrors returns the value of Errors.
func (s *Problem) GetErrors() []ProblemErrorsItem {
	return s.Errors
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetTraceID sets the value of TraceID.
func (s *Problem) SetTraceID(val OptString) {
	s.TraceID = val
}

// SetErrors sets the value of Errors.
func (s *Problem) SetErrors(val []ProblemErrorsItem) {
	s.Errors = val
}

type ProblemErrorsItem struct {
	// RFC 6901 JSON Pointer to the offending member.
	Pointer string `json:"pointer"`
	Message string `json:"message"`
}

// GetPointer returns the value of Pointer.
func (s *ProblemErrorsItem) GetPointer() string {
	return s.Pointer
}

// GetMessage returns the value of Message.
func (s *ProblemErrorsItem) GetMessage() string {
	return s.Message
}

// SetPointer sets the value of Pointer.
func (s *ProblemErrorsItem) SetPointer(val string) {
	s.Pointer = val
}

// SetMessage sets the value of Message.
func (s *ProblemErrorsItem) SetMessage(val string) {
	s.Message = val
}

// A catalog product.
// Ref: #/components/schemas/Product
type Product struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	PriceCents int       `json:"price_cents"`
}

// GetID returns the value of ID.
func (s *Product) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Product) GetName() string {
	return s.Name
}

// GetPriceCents returns the value of PriceCents.
func (s *Product) GetPriceCents() int {
	return s.PriceCents
}

// SetID sets the value of ID.
func (s *Product) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Product) SetName(val string) {
	s.Name = val
}

// SetPriceCents sets the value of PriceCents.
func (s *Product) SetPriceCents(val int) {
	s.PriceCents = val
}

// Request body to create a product.
// Ref: #/components/schemas/ProductInput
type ProductInput struct {
	Name       string `json:"name"`
	PriceCents int    `json:"price_cents"`
}

// GetName returns the value of Name.
func (s *ProductInput) GetName() string {
	return s.Name
}

// GetPriceCents returns the value of PriceCents.
func (s *ProductInput) GetPriceCents() int {
	return s.PriceCents
}

// SetName sets the value of Name.
func (s *ProductInput) SetName(val string) {
	s.Name = val
}

// SetPriceCents sets the value of PriceCents.
func (s *ProductInput) SetPriceCents(val int) {
	s.PriceCents = val
}
