/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all organizations. */
        get: operations["listOrgs"];
        put?: never;
        /** @description Create an organization. */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an organization by id. */
        get: operations["getOrg"];
        /** @description Rename an organization. */
        put: operations["updateOrg"];
        post?: never;
        /** @description Delete an organization. */
        delete: operations["deleteOrg"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Kratos post-registration webhook. Creates a personal org for the new identity. */
        post: operations["onIdentityCreated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Served as `application/problem+json` by services and
         *     by the edge alike, so a generated client has one error branch rather than two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case takes a `urn:problem-type:<service>:<slug>`
             *     URN — never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. Does not vary with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, duplicated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Instance-specific and safe to show a user. Never a stack trace, a query, or
             *     an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so a user-reported
             *     error reaches its trace. Supplied from the active span, not by the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, populated from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the offending member.
                 * @example /price_cents
                 */
                pointer: string;
                /** @example must be greater than or equal to 0 */
                message: string;
            }[];
        };
        /**
         * @description A monetary amount. The amount is a decimal STRING — a JSON number becomes a
         *     double in the TypeScript client, and a double cannot hold a decimal amount
         *     exactly. Currency travels with the amount, because an amount without one is
         *     not a quantity of anything.
         * @example {
         *       "amount": "1299.00",
         *       "currency": "EUR"
         *     }
         */
        Money: {
            /**
             * @description Decimal amount, sign-prefixed when negative. No thousands separators.
             * @example 1299.00
             */
            amount: string;
            /**
             * @description ISO 4217 alphabetic code, uppercase.
             * @example EUR
             */
            currency: string;
        };
        /**
         * Format: date-time
         * @description RFC 3339 timestamp in UTC with a literal `Z`. An offset other than `Z` is
         *     rejected rather than converted. Columns behind these are Postgres `timestamptz`.
         * @example 2026-08-12T09:30:00Z
         */
        Timestamp: string;
        /**
         * @description An organization.
         * @example {
         *       "id": "4a8b2d63-9e15-4c70-8d21-0f27f7f0a001",
         *       "name": "Northwind Trading"
         *     }
         */
        Org: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @description Request body to create an organization. */
        OrgInput: {
            name: string;
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The organization to create. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the organization to update. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The new organization fields. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgInput"];
            };
        };
        responses: {
            /** @description The updated organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the organization to delete. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    onIdentityCreated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The newly created identity. */
        requestBody: {
            content: {
                "application/json": {
                    identity_id?: string;
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Ack */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
