/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an organization. */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an organization by id. */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/identity-created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Kratos post-registration webhook. Creates a personal org for the new identity. */
        post: operations["onIdentityCreated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem document. */
        Problem: {
            /** @example not_found */
            code: string;
            /** @example organization not found */
            message: string;
            /**
             * @example {
             *       "field": "name"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description An organization. */
        Org: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /** @example Acme Inc */
            name: string;
        };
        /** @description Request body to create an organization. */
        OrgInput: {
            /** @example Acme Inc */
            name: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The organization to create. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    onIdentityCreated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The newly created identity. */
        requestBody: {
            content: {
                "application/json": {
                    /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
                    identity_id?: string;
                    /** @example ada@example.com */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Ack */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
