// Code generated by ogen, DO NOT EDIT.

package orders

import (
	"fmt"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Request body to start a checkout.
// Ref: #/components/schemas/CheckoutInput
type CheckoutInput struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int       `json:"quantity"`
}

// GetProductID returns the value of ProductID.
func (s *CheckoutInput) GetProductID() uuid.UUID {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *CheckoutInput) GetQuantity() int {
	return s.Quantity
}

// SetProductID sets the value of ProductID.
func (s *CheckoutInput) SetProductID(val uuid.UUID) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *CheckoutInput) SetQuantity(val int) {
	s.Quantity = val
}

// ErrorStatusCode wraps Problem with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// A customer order.
// Ref: #/components/schemas/Order
type Order struct {
	ID         uuid.UUID   `json:"id"`
	ProductID  uuid.UUID   `json:"product_id"`
	Quantity   int         `json:"quantity"`
	TotalCents int         `json:"total_cents"`
	Status     OrderStatus `json:"status"`
}

// GetID returns the value of ID.
func (s *Order) GetID() uuid.UUID {
	return s.ID
}

// GetProductID returns the value of ProductID.
func (s *Order) GetProductID() uuid.UUID {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *Order) GetQuantity() int {
	return s.Quantity
}

// GetTotalCents returns the value of TotalCents.
func (s *Order) GetTotalCents() int {
	return s.TotalCents
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetID sets the value of ID.
func (s *Order) SetID(val uuid.UUID) {
	s.ID = val
}

// SetProductID sets the value of ProductID.
func (s *Order) SetProductID(val uuid.UUID) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *Order) SetQuantity(val int) {
	s.Quantity = val
}

// SetTotalCents sets the value of TotalCents.
func (s *Order) SetTotalCents(val int) {
	s.TotalCents = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusFailed    OrderStatus = "failed"
	OrderStatusCancelled OrderStatus = "cancelled"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPending,
		OrderStatusConfirmed,
		OrderStatusFailed,
		OrderStatusCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPending:
		return []byte(s), nil
	case OrderStatusConfirmed:
		return []byte(s), nil
	case OrderStatusFailed:
		return []byte(s), nil
	case OrderStatusCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPending:
		*s = OrderStatusPending
		return nil
	case OrderStatusConfirmed:
		*s = OrderStatusConfirmed
		return nil
	case OrderStatusFailed:
		*s = OrderStatusFailed
		return nil
	case OrderStatusCancelled:
		*s = OrderStatusCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// RFC 9457 problem details. Served as `application/problem+json` by services and by the edge alike, so
// a generated client has one error branch rather than two.
// Ref: #/components/schemas/Problem
type Problem struct {
	// `about:blank`, except where two errors share a status code and a client handles them differently.
	// That case takes a `urn:problem-type:<service>:<slug>` URN — never a dereferenceable URL, which
	// would put an error taxonomy into the flat public URL namespace.
	Type string `json:"type"`
	// A stable, human-readable summary. Does not vary with the instance.
	Title string `json:"title"`
	// The HTTP status, duplicated in the body.
	Status int `json:"status"`
	// Instance-specific and safe to show a user. Never a stack trace, a query, or an internal hostname.
	Detail OptString `json:"detail"`
	// The W3C Trace Context trace-id of the failing request, so a user-reported error reaches its trace.
	// Supplied from the active span, not by the handler.
	TraceID OptString `json:"trace_id"`
	// Field-level validation failures, populated from the generated validator. Absent when the failure is
	// not a validation failure.
	Errors []ProblemErrorsItem `json:"errors"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetTraceID returns the value of TraceID.
func (s *Problem) GetTraceID() OptString {
	return s.TraceID
}

// GetErrors returns the value of Errors.
func (s *Problem) GetErrors() []ProblemErrorsItem {
	return s.Errors
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetTraceID sets the value of TraceID.
func (s *Problem) SetTraceID(val OptString) {
	s.TraceID = val
}

// SetErrors sets the value of Errors.
func (s *Problem) SetErrors(val []ProblemErrorsItem) {
	s.Errors = val
}

type ProblemErrorsItem struct {
	// RFC 6901 JSON Pointer to the offending member.
	Pointer string `json:"pointer"`
	Message string `json:"message"`
}

// GetPointer returns the value of Pointer.
func (s *ProblemErrorsItem) GetPointer() string {
	return s.Pointer
}

// GetMessage returns the value of Message.
func (s *ProblemErrorsItem) GetMessage() string {
	return s.Message
}

// SetPointer sets the value of Pointer.
func (s *ProblemErrorsItem) SetPointer(val string) {
	s.Pointer = val
}

// SetMessage sets the value of Message.
func (s *ProblemErrorsItem) SetMessage(val string) {
	s.Message = val
}

// Handle to an async Temporal workflow run.
// Ref: #/components/schemas/WorkflowHandle
type WorkflowHandle struct {
	ID     string               `json:"id"`
	RunID  string               `json:"run_id"`
	Status WorkflowHandleStatus `json:"status"`
	// GET to fetch terminal status + result.
	ResultURL OptURI `json:"result_url"`
}

// GetID returns the value of ID.
func (s *WorkflowHandle) GetID() string {
	return s.ID
}

// GetRunID returns the value of RunID.
func (s *WorkflowHandle) GetRunID() string {
	return s.RunID
}

// GetStatus returns the value of Status.
func (s *WorkflowHandle) GetStatus() WorkflowHandleStatus {
	return s.Status
}

// GetResultURL returns the value of ResultURL.
func (s *WorkflowHandle) GetResultURL() OptURI {
	return s.ResultURL
}

// SetID sets the value of ID.
func (s *WorkflowHandle) SetID(val string) {
	s.ID = val
}

// SetRunID sets the value of RunID.
func (s *WorkflowHandle) SetRunID(val string) {
	s.RunID = val
}

// SetStatus sets the value of Status.
func (s *WorkflowHandle) SetStatus(val WorkflowHandleStatus) {
	s.Status = val
}

// SetResultURL sets the value of ResultURL.
func (s *WorkflowHandle) SetResultURL(val OptURI) {
	s.ResultURL = val
}

type WorkflowHandleStatus string

const (
	WorkflowHandleStatusRunning   WorkflowHandleStatus = "running"
	WorkflowHandleStatusCompleted WorkflowHandleStatus = "completed"
	WorkflowHandleStatusFailed    WorkflowHandleStatus = "failed"
	WorkflowHandleStatusCancelled WorkflowHandleStatus = "cancelled"
)

// AllValues returns all WorkflowHandleStatus values.
func (WorkflowHandleStatus) AllValues() []WorkflowHandleStatus {
	return []WorkflowHandleStatus{
		WorkflowHandleStatusRunning,
		WorkflowHandleStatusCompleted,
		WorkflowHandleStatusFailed,
		WorkflowHandleStatusCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkflowHandleStatus) MarshalText() ([]byte, error) {
	switch s {
	case WorkflowHandleStatusRunning:
		return []byte(s), nil
	case WorkflowHandleStatusCompleted:
		return []byte(s), nil
	case WorkflowHandleStatusFailed:
		return []byte(s), nil
	case WorkflowHandleStatusCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkflowHandleStatus) UnmarshalText(data []byte) error {
	switch WorkflowHandleStatus(data) {
	case WorkflowHandleStatusRunning:
		*s = WorkflowHandleStatusRunning
		return nil
	case WorkflowHandleStatusCompleted:
		*s = WorkflowHandleStatusCompleted
		return nil
	case WorkflowHandleStatusFailed:
		*s = WorkflowHandleStatusFailed
		return nil
	case WorkflowHandleStatusCancelled:
		*s = WorkflowHandleStatusCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
