/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Starts the Charge Temporal workflow. Idempotent on Idempotency-Key header.
         *     Returns a workflow handle (ADR-0006).
         */
        post: operations["createCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a charge by id. */
        get: operations["getCharge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem document. */
        Problem: {
            /** @example not_found */
            code: string;
            /** @example charge not found */
            message: string;
            /**
             * @example {
             *       "field": "order_id"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Handle to an async Temporal workflow run. */
        WorkflowHandle: {
            /** @example charge-7f3a */
            id: string;
            /** @example 9b1c2d3e-4f56-7890-abcd-ef0123456789 */
            run_id: string;
            /**
             * @example running
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             * @example /api/payment/charges/charge-7f3a
             */
            result_url?: string;
        };
        /** @description Request body to create a charge. */
        ChargeInput: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            order_id: string;
            /** @example 1999 */
            amount_cents: number;
        };
        /** @description A payment charge against an order. */
        Charge: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            order_id: string;
            /** @example 1999 */
            amount_cents: number;
            /**
             * @example settled
             * @enum {string}
             */
            status: "pending" | "settled" | "failed" | "refunded";
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCharge: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated key that makes the charge request idempotent. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description The charge to create. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChargeInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Charge id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
