/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all charges. */
        get: operations["listCharges"];
        put?: never;
        /**
         * @description Starts the Charge Temporal workflow. Idempotent on Idempotency-Key header.
         *     Returns a workflow handle (ADR-0302).
         */
        post: operations["createCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a charge by id. */
        get: operations["getCharge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Refund a settled charge. Starts the Refund workflow (ADR-0302). */
        post: operations["refundCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Served as `application/problem+json` by services and
         *     by the edge alike, so a generated client has one error branch rather than two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case takes a `urn:problem-type:<service>:<slug>`
             *     URN — never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. Does not vary with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, duplicated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Instance-specific and safe to show a user. Never a stack trace, a query, or
             *     an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so a user-reported
             *     error reaches its trace. Supplied from the active span, not by the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, populated from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the offending member.
                 * @example /price_cents
                 */
                pointer: string;
                /** @example must be greater than or equal to 0 */
                message: string;
            }[];
        };
        /**
         * @description A monetary amount. The amount is a decimal STRING — a JSON number becomes a
         *     double in the TypeScript client, and a double cannot hold a decimal amount
         *     exactly. Currency travels with the amount, because an amount without one is
         *     not a quantity of anything.
         * @example {
         *       "amount": "1299.00",
         *       "currency": "EUR"
         *     }
         */
        Money: {
            /**
             * @description Decimal amount, sign-prefixed when negative. No thousands separators.
             * @example 1299.00
             */
            amount: string;
            /**
             * @description ISO 4217 alphabetic code, uppercase.
             * @example EUR
             */
            currency: string;
        };
        /**
         * Format: date-time
         * @description RFC 3339 timestamp in UTC with a literal `Z`. An offset other than `Z` is
         *     rejected rather than converted. Columns behind these are Postgres `timestamptz`.
         * @example 2026-08-12T09:30:00Z
         */
        Timestamp: string;
        /**
         * @description Handle to an async Temporal workflow run.
         * @example {
         *       "id": "charge-7d1e4a95-3c82-4f17-9b06-0f27f7f0f001",
         *       "run_id": "019a3f8c-6d21-7c4b-8e55-0f27f7f0e002",
         *       "status": "running",
         *       "result_url": "/api/charges/7d1e4a95-3c82-4f17-9b06-0f27f7f0f001"
         *     }
         */
        WorkflowHandle: {
            id: string;
            run_id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             */
            result_url?: string;
        };
        /** @description Request body to create a charge. */
        ChargeInput: {
            /** Format: uuid */
            order_id: string;
            amount_cents: number;
        };
        /** @description Request body to refund a charge. */
        RefundInput: {
            reason: string;
        };
        /**
         * @description A payment charge against an order.
         * @example {
         *       "id": "7d1e4a95-3c82-4f17-9b06-0f27f7f0f001",
         *       "order_id": "2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001",
         *       "amount_cents": 259800,
         *       "status": "settled"
         *     }
         */
        Charge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            amount_cents: number;
            /** @enum {string} */
            status: "pending" | "settled" | "failed" | "refunded";
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCharges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The charge list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCharge: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated key that makes the charge request idempotent. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description The charge to create. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChargeInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Charge id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refundCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the charge to refund. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The refund request. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundInput"];
            };
        };
        responses: {
            /** @description Refund accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
