/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Starts the Charge Temporal workflow. Idempotent on Idempotency-Key header.
         *     Returns a workflow handle (ADR-0006).
         */
        post: operations["createCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a charge by id. */
        get: operations["getCharge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkflowHandle: {
            id: string;
            run_id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             */
            result_url?: string;
        };
        ChargeInput: {
            /** Format: uuid */
            order_id: string;
            amount_cents: number;
        };
        Charge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            amount_cents: number;
            /** @enum {string} */
            status: "pending" | "settled" | "failed" | "refunded";
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /** @example not_found */
                    code: string;
                    message: string;
                    details?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCharge: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChargeInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
