/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all orders. */
        get: operations["listOrders"];
        put?: never;
        /** @description Starts the Checkout Temporal saga (ADR-0302). */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an order by id. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel an order. Starts the CancelOrder workflow (ADR-0302). */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Served as `application/problem+json` by services and
         *     by the edge alike, so a generated client has one error branch rather than two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case takes a `urn:problem-type:<service>:<slug>`
             *     URN — never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. Does not vary with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, duplicated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Instance-specific and safe to show a user. Never a stack trace, a query, or
             *     an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so a user-reported
             *     error reaches its trace. Supplied from the active span, not by the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, populated from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the offending member.
                 * @example /price_cents
                 */
                pointer: string;
                /** @example must be greater than or equal to 0 */
                message: string;
            }[];
        };
        /**
         * @description A monetary amount. The amount is a decimal STRING — a JSON number becomes a
         *     double in the TypeScript client, and a double cannot hold a decimal amount
         *     exactly. Currency travels with the amount, because an amount without one is
         *     not a quantity of anything.
         * @example {
         *       "amount": "1299.00",
         *       "currency": "EUR"
         *     }
         */
        Money: {
            /**
             * @description Decimal amount, sign-prefixed when negative. No thousands separators.
             * @example 1299.00
             */
            amount: string;
            /**
             * @description ISO 4217 alphabetic code, uppercase.
             * @example EUR
             */
            currency: string;
        };
        /**
         * Format: date-time
         * @description RFC 3339 timestamp in UTC with a literal `Z`. An offset other than `Z` is
         *     rejected rather than converted. Columns behind these are Postgres `timestamptz`.
         * @example 2026-08-12T09:30:00Z
         */
        Timestamp: string;
        /**
         * @description Handle to an async Temporal workflow run.
         * @example {
         *       "id": "checkout-2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001",
         *       "run_id": "019a3f8c-6d21-7c4b-8e55-0f27f7f0e001",
         *       "status": "running",
         *       "result_url": "/api/orders/2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001"
         *     }
         */
        WorkflowHandle: {
            id: string;
            run_id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             */
            result_url?: string;
        };
        /** @description Request body to start a checkout. */
        CheckoutInput: {
            /** Format: uuid */
            product_id: string;
            quantity: number;
        };
        /**
         * @description A customer order.
         * @example {
         *       "id": "2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001",
         *       "product_id": "6f7a1c48-1a9d-4b1e-9a2c-0f27f7f0c001",
         *       "quantity": 2,
         *       "total_cents": 259800,
         *       "status": "confirmed"
         *     }
         */
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            quantity: number;
            total_cents: number;
            /** @enum {string} */
            status: "pending" | "confirmed" | "failed" | "cancelled";
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The checkout to start. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the order to cancel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
