/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts the Checkout Temporal saga (ADR-0006). */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an order by id. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem document. */
        Problem: {
            /** @example not_found */
            code: string;
            /** @example order not found */
            message: string;
            /**
             * @example {
             *       "field": "product_id"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Handle to an async Temporal workflow run. */
        WorkflowHandle: {
            /** @example checkout-7f3a */
            id: string;
            /** @example 9b1c2d3e-4f56-7890-abcd-ef0123456789 */
            run_id: string;
            /**
             * @example running
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             * @example /api/orders/orders/7f3a
             */
            result_url?: string;
        };
        /** @description Request body to start a checkout. */
        CheckoutInput: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            product_id: string;
            /** @example 2 */
            quantity: number;
        };
        /** @description A customer order. */
        Order: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            product_id: string;
            /** @example 2 */
            quantity: number;
            /** @example 3998 */
            total_cents: number;
            /**
             * @example confirmed
             * @enum {string}
             */
            status: "pending" | "confirmed" | "failed";
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The checkout to start. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
