// Code generated by ogen, DO NOT EDIT.

package analytics

// OperationName is the ogen operation name
type OperationName = string

const (
	GetConsentOperation    OperationName = "GetConsent"
	RecordConsentOperation OperationName = "RecordConsent"
	RecordEventsOperation  OperationName = "RecordEvents"
)
