// Code generated by ogen, DO NOT EDIT.

package analytics

import (
	"net/http"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetConsentParams is parameters of getConsent operation.
type GetConsentParams struct {
	// The session to read.
	SessionID string
}

func unpackGetConsentParams(packed middleware.Parameters) (params GetConsentParams) {
	{
		key := middleware.ParameterKey{
			Name: "session_id",
			In:   "query",
		}
		params.SessionID = packed[key].(string)
	}
	return params
}

func decodeGetConsentParams(args [0]string, argsEscaped bool, r *http.Request) (params GetConsentParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: session_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "session_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.SessionID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SummariseEventsParams is parameters of summariseEvents operation.
type SummariseEventsParams struct {
	// The start of the window.
	Since time.Time
}

func unpackSummariseEventsParams(packed middleware.Parameters) (params SummariseEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "since",
			In:   "query",
		}
		params.Since = packed[key].(time.Time)
	}
	return params
}

func decodeSummariseEventsParams(args [0]string, argsEscaped bool, r *http.Request) (params SummariseEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: since.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "since",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.Since = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "since",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
