// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsent = `-- name: GetConsent :one
select
  session_id,
  identity_id,
  state,
  purpose_version,
  source,
  decided_at
from consent
where session_id = $1
`

type GetConsentRow struct {
	SessionID      string             `json:"session_id"`
	IdentityID     pgtype.Text        `json:"identity_id"`
	State          string             `json:"state"`
	PurposeVersion string             `json:"purpose_version"`
	Source         string             `json:"source"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
}

func (q *Queries) GetConsent(ctx context.Context, sessionID string) (GetConsentRow, error) {
	row := q.db.QueryRow(ctx, getConsent, sessionID)
	var i GetConsentRow
	err := row.Scan(
		&i.SessionID,
		&i.IdentityID,
		&i.State,
		&i.PurposeVersion,
		&i.Source,
		&i.DecidedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
insert into events (
  id, session_id, identity_id, name, properties, device_class, occurred_at
)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   string             `json:"session_id"`
	IdentityID  pgtype.Text        `json:"identity_id"`
	Name        string             `json:"name"`
	Properties  []byte             `json:"properties"`
	DeviceClass string             `json:"device_class"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.SessionID,
		arg.IdentityID,
		arg.Name,
		arg.Properties,
		arg.DeviceClass,
		arg.OccurredAt,
	)
	return err
}

const upsertConsent = `-- name: UpsertConsent :one
insert into consent (session_id, identity_id, state, purpose_version, source)
values ($1, $2, $3, $4, $5)
on conflict (session_id) do update set
identity_id = excluded.identity_id,
state = excluded.state,
purpose_version = excluded.purpose_version,
source = excluded.source,
updated_at = now()
returning session_id, identity_id, state, purpose_version, source, decided_at
`

type UpsertConsentParams struct {
	SessionID      string      `json:"session_id"`
	IdentityID     pgtype.Text `json:"identity_id"`
	State          string      `json:"state"`
	PurposeVersion string      `json:"purpose_version"`
	Source         string      `json:"source"`
}

type UpsertConsentRow struct {
	SessionID      string             `json:"session_id"`
	IdentityID     pgtype.Text        `json:"identity_id"`
	State          string             `json:"state"`
	PurposeVersion string             `json:"purpose_version"`
	Source         string             `json:"source"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
}

// A decision replaces the previous one for the session and keeps the row, because
// withdrawal is a state rather than a deletion: erasing it would erase the evidence
// that consent was once given, which is what GDPR Art. 7(1) asks to be demonstrable.
func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) (UpsertConsentRow, error) {
	row := q.db.QueryRow(ctx, upsertConsent,
		arg.SessionID,
		arg.IdentityID,
		arg.State,
		arg.PurposeVersion,
		arg.Source,
	)
	var i UpsertConsentRow
	err := row.Scan(
		&i.SessionID,
		&i.IdentityID,
		&i.State,
		&i.PurposeVersion,
		&i.Source,
		&i.DecidedAt,
	)
	return i, err
}
