// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Consent struct {
	// pii:identifier
	SessionID string `json:"session_id"`
	// pii:identifier
	IdentityID pgtype.Text `json:"identity_id"`
	// pii:none
	State string `json:"state"`
	// pii:none
	PurposeVersion string `json:"purpose_version"`
	// pii:none
	Source    string             `json:"source"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID pgtype.UUID `json:"id"`
	// pii:identifier
	SessionID string `json:"session_id"`
	// pii:identifier
	IdentityID pgtype.Text `json:"identity_id"`
	// pii:none
	Name string `json:"name"`
	// pii:free_text
	Properties []byte `json:"properties"`
	// pii:device
	DeviceClass string             `json:"device_class"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
