// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetConsent(ctx context.Context, sessionID string) (GetConsentRow, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	// A decision replaces the previous one for the session and keeps the row, because
	// withdrawal is a state rather than a deletion: erasing it would erase the evidence
	// that consent was once given, which is what GDPR Art. 7(1) asks to be demonstrable.
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) (UpsertConsentRow, error)
}

var _ Querier = (*Queries)(nil)
