// Code generated by ogen, DO NOT EDIT.

package orders

import (
	"fmt"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CheckoutInput
type CheckoutInput struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int       `json:"quantity"`
}

// GetProductID returns the value of ProductID.
func (s *CheckoutInput) GetProductID() uuid.UUID {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *CheckoutInput) GetQuantity() int {
	return s.Quantity
}

// SetProductID sets the value of ProductID.
func (s *CheckoutInput) SetProductID(val uuid.UUID) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *CheckoutInput) SetQuantity(val int) {
	s.Quantity = val
}

type Error struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Details OptErrorDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() OptErrorDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val OptErrorDetails) {
	s.Details = val
}

type ErrorDetails map[string]jx.Raw

func (s *ErrorDetails) init() ErrorDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptErrorDetails returns new OptErrorDetails with value set to v.
func NewOptErrorDetails(v ErrorDetails) OptErrorDetails {
	return OptErrorDetails{
		Value: v,
		Set:   true,
	}
}

// OptErrorDetails is optional ErrorDetails.
type OptErrorDetails struct {
	Value ErrorDetails
	Set   bool
}

// IsSet returns true if OptErrorDetails was set.
func (o OptErrorDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorDetails) Reset() {
	var v ErrorDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorDetails) SetTo(v ErrorDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorDetails) Get() (v ErrorDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorDetails) Or(d ErrorDetails) ErrorDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Order
type Order struct {
	ID         uuid.UUID   `json:"id"`
	ProductID  uuid.UUID   `json:"product_id"`
	Quantity   int         `json:"quantity"`
	TotalCents int         `json:"total_cents"`
	Status     OrderStatus `json:"status"`
}

// GetID returns the value of ID.
func (s *Order) GetID() uuid.UUID {
	return s.ID
}

// GetProductID returns the value of ProductID.
func (s *Order) GetProductID() uuid.UUID {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *Order) GetQuantity() int {
	return s.Quantity
}

// GetTotalCents returns the value of TotalCents.
func (s *Order) GetTotalCents() int {
	return s.TotalCents
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetID sets the value of ID.
func (s *Order) SetID(val uuid.UUID) {
	s.ID = val
}

// SetProductID sets the value of ProductID.
func (s *Order) SetProductID(val uuid.UUID) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *Order) SetQuantity(val int) {
	s.Quantity = val
}

// SetTotalCents sets the value of TotalCents.
func (s *Order) SetTotalCents(val int) {
	s.TotalCents = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusFailed    OrderStatus = "failed"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPending,
		OrderStatusConfirmed,
		OrderStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPending:
		return []byte(s), nil
	case OrderStatusConfirmed:
		return []byte(s), nil
	case OrderStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPending:
		*s = OrderStatusPending
		return nil
	case OrderStatusConfirmed:
		*s = OrderStatusConfirmed
		return nil
	case OrderStatusFailed:
		*s = OrderStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/WorkflowHandle
type WorkflowHandle struct {
	ID     string               `json:"id"`
	RunID  string               `json:"run_id"`
	Status WorkflowHandleStatus `json:"status"`
	// GET to fetch terminal status + result.
	ResultURL OptURI `json:"result_url"`
}

// GetID returns the value of ID.
func (s *WorkflowHandle) GetID() string {
	return s.ID
}

// GetRunID returns the value of RunID.
func (s *WorkflowHandle) GetRunID() string {
	return s.RunID
}

// GetStatus returns the value of Status.
func (s *WorkflowHandle) GetStatus() WorkflowHandleStatus {
	return s.Status
}

// GetResultURL returns the value of ResultURL.
func (s *WorkflowHandle) GetResultURL() OptURI {
	return s.ResultURL
}

// SetID sets the value of ID.
func (s *WorkflowHandle) SetID(val string) {
	s.ID = val
}

// SetRunID sets the value of RunID.
func (s *WorkflowHandle) SetRunID(val string) {
	s.RunID = val
}

// SetStatus sets the value of Status.
func (s *WorkflowHandle) SetStatus(val WorkflowHandleStatus) {
	s.Status = val
}

// SetResultURL sets the value of ResultURL.
func (s *WorkflowHandle) SetResultURL(val OptURI) {
	s.ResultURL = val
}

type WorkflowHandleStatus string

const (
	WorkflowHandleStatusRunning   WorkflowHandleStatus = "running"
	WorkflowHandleStatusCompleted WorkflowHandleStatus = "completed"
	WorkflowHandleStatusFailed    WorkflowHandleStatus = "failed"
	WorkflowHandleStatusCancelled WorkflowHandleStatus = "cancelled"
)

// AllValues returns all WorkflowHandleStatus values.
func (WorkflowHandleStatus) AllValues() []WorkflowHandleStatus {
	return []WorkflowHandleStatus{
		WorkflowHandleStatusRunning,
		WorkflowHandleStatusCompleted,
		WorkflowHandleStatusFailed,
		WorkflowHandleStatusCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkflowHandleStatus) MarshalText() ([]byte, error) {
	switch s {
	case WorkflowHandleStatusRunning:
		return []byte(s), nil
	case WorkflowHandleStatusCompleted:
		return []byte(s), nil
	case WorkflowHandleStatusFailed:
		return []byte(s), nil
	case WorkflowHandleStatusCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkflowHandleStatus) UnmarshalText(data []byte) error {
	switch WorkflowHandleStatus(data) {
	case WorkflowHandleStatusRunning:
		*s = WorkflowHandleStatusRunning
		return nil
	case WorkflowHandleStatusCompleted:
		*s = WorkflowHandleStatusCompleted
		return nil
	case WorkflowHandleStatusFailed:
		*s = WorkflowHandleStatusFailed
		return nil
	case WorkflowHandleStatusCancelled:
		*s = WorkflowHandleStatusCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
